auth:
  image: datopian/datahub-auth:67f55287cf916880fe89090dd645e230c80c17a0-451750555
factory:
  image: datopian/factory:284aa1de8c5f065152328b06319cff851d453174-99580759
filemanager:
  image: datopian/filemanager:905b1cfca0a6874d2e79e7940a8dd1055dcb955b
frontend:
  image: datopian/datahub-frontend:0dc9a0f6750e55a7aff89783b58af42054c95fa4-655771845
metastore:
  image: datopian/metastore:c30f16711d984213aca50ad731f7cce347c902bc-425582464
nginx:
  image: datopian/datahub-nginx:dc31b8b19619bdce13affd125a19fda69178aec7-443669231
plans:
  image: datopian/plans:12bd9ff6f725703e7a73f3ad90680f5ade8cebdf
rawstore:
  image: datopian/bitstore:9eac273b288905c865fd5ce12bf136b4e02ae3cb-451750559
resolver:
  image: datopian/resolver:a897a90021432691ace81974dd261e48ee34fc95
specstore:
  image: datopian/specstore:83311d17a8d4d27290e8a80766c2aaa06c8fe0cb-451750557
